### PR TITLE
Refactors requests to use a single method.

### PR DESCRIPTION
**Pull request by wsaglime**
Several change ideas:

- refactor requests to use a wrapped method, so there is less copy-and-paste code.
- added python3 shebang line.
- protected code with an ```if __name__ == "__main__"``` wrapper so it doesn't accidentally execute requests if you use these methods from another python file.
- renamed "count" and "sum" methods because "sum" was already a python builtin method and "count" is used in lots of generic libraries.
- organized imports because I have rampant OCD when it comes to making it obvious which imports are standard library and don't need pip installs, which are third-party and therefore need installs, and which are local and need code files. 

Thanks for offering to consider pull requests!

PS Found your code through https://www.reddit.com/r/todoist/comments/9x2vtt/script_to_sum_estimated_time_for_tasks_via_labels/, when I asked Google if there was a Todoist plugin for summing up estimate time for tasks. I love it! Thanks for writing it, and also writing such a nice readme to make contributions easy 👍

### CODE REVIEW

**Comment by minthemiddle** [comment]
Hi, @wsaglime, thanks for your Pull Request. For some reasons, Github did not send me notifications. I'll look through it and see that I can merge as soon as possible!

**Comment by wsaglime** [comment]
Great! Let me know if you like some ideas but want changes. Thanks for
making the repo and putting it out there as open source!

**Comment by minthemiddle** [comment]
Such a nice pull request. Thanks a million, @wsaglime - this makes it much cleaner, simpler and easier to extend.

**Comment by wsaglime** [comment]
Yay, thanks for reading and merging :) And putting the code out there in
the first place, good stuff!

**Pull request merged**
